name: test-sbom-generator

on: 
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  sbom-generation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          echo '$GITHUB_ACTION_PATH'
          pip install -r $GITHUB_ACTION_PATH/requirements.txt
        shell: bash 
      - name: Checkout the FreeRTOS/corePKCS11 repository for testing action on.
        uses: actions/checkout@v2
        with:
          repository: FreeRTOS/corePKCS11
          ref: main
          path: corePKCS11
          submodules: recursive    
      - name: Run generator script
        working-directory: ./corePKCS11
        run: |
          python3 $GITHUB_ACTION_PATH/scan_corePKCS11.py
        shell: bash
      - name: create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: update-sbom
          token: ${{ github.token }}
          path: ./corePKCS11
          commit-message: Add sbom file
          title: 'Add sbom file'
          body: >
            This PR is auto-generated by
            [create-pull-request](https://github.com/peter-evans/create-pull-request).
          tag: 'SBOM'

