name: SBOM Generation

on:
  pull_request:
    branches: [main]

jobs:
  sbom:
    if: github.head_ref != 'update-sbom'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check doxygen build
        uses: xlin7799/CI-CD-Github-Actions/sbom-generator@main
        with:
          path: ./
          token: ${{ github.token }}
          script: scan_corePKCS11.py
